### ISSUE TITLE
violation doesn't have type model

### ISSUE THREAD

**Issue by fgregg** [security-force-monitor/sfm-cms#557]
Following the instructions in the readme, I am stuck at loading violation_types @evz 

```bash
>./manage.py loaddata violation_types
System check identified some issues:

WARNINGS:
languages_plus.Language.countries_spoken: (fields.W340) null has no effect on ManyToManyField.
Traceback (most recent call last):
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/apps/config.py", line 169, in get_model
    return self.models[model_name.lower()]
KeyError: 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/core/serializers/python.py", line 192, in _get_model
    return apps.get_model(model_identifier)
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/apps/registry.py", line 205, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/apps/config.py", line 172, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'violation' doesn't have a 'type' model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/core/serializers/json.py", line 82, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/core/serializers/python.py", line 99, in Deserializer
    Model = _get_model(d["model"])
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/core/serializers/python.py", line 194, in _get_model
    raise base.DeserializationError("Invalid model identifier: '%s'" % model_identifier)
django.core.serializers.base.DeserializationError: Invalid model identifier: 'violation.type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
    self.loaddata(fixture_labels)
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 109, in loaddata
    self.load_label(fixture_label)
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 166, in load_label
    for obj in objects:
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/core/serializers/json.py", line 88, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/core/serializers/json.py", line 82, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/core/serializers/python.py", line 99, in Deserializer
    Model = _get_model(d["model"])
  File "/Users/fgregg/work/sfm-cms/.env/lib/python3.7/site-packages/django/core/serializers/python.py", line 194, in _get_model
    raise base.DeserializationError("Invalid model identifier: '%s'" % model_identifier)
django.core.serializers.base.DeserializationError: Problem installing fixture '/Users/fgregg/work/sfm-cms/violation/fixtures/violation_types.json': Invalid model identifier: 'violation.type'
```

```
> pip freeze
atomicwrites==1.2.1
attrs==18.2.0
certifi==2018.11.29
chardet==3.0.4
datefinder==0.6.0
dateparser==0.7.0
dj-database-url==0.3.0
Django==1.11.18
django-bootstrap-pagination==1.6.2
-e git+https://github.com/security-force-monitor/complex_fields.git@328aef79a458fb568f9917929f9817c8c73f729c#egg=django_complex_fields
django-countries-plus==1.1
django-date-extensions==2.0
django-debug-toolbar==1.11
django-extra-views==0.7.1
django-jsonview==0.5.0
django-languages-plus==0.1.5
django-leaflet==0.16.0
django-localeurl==2.0.2
django-reversion==2.0.4
django-rosetta==0.7.13
google-api-python-client==1.5.4
gunicorn==19.0.0
httplib2==0.12.0
idna==2.8
microsofttranslator==0.8
more-itertools==5.0.0
oauth2client==4.1.3
pluggy==0.8.1
polib==1.1.0
psycopg2==2.7.3.1
py==1.7.0
pyasn1==0.4.5
pyasn1-modules==0.2.4
pysolr==3.6.0
pytest==4.2.0
pytest-django==3.3.3
pytest-mock==1.10.0
python-dateutil==2.7.5
pytz==2018.9
raven==6.10.0
regex==2019.1.24
requests==2.21.0
rsa==4.0
six==1.12.0
SQLAlchemy==1.1.3
sqlparse==0.2.4
tzlocal==1.5.1
uritemplate==3.0.0
urllib3==1.24.1
```

**Comment by fgregg** [comment]
@evz not all migrations are under VC.

**Comment by fgregg** [comment]
traceback of ./manage migrate --noinput

```bash
/manage.py migrate --noinput
System check identified some issues:

WARNINGS:
languages_plus.Language.countries_spoken: (fields.W340) null has no effect on ManyToManyField.
Operations to perform:
  Apply all migrations: admin, area, association, auth, composition, contenttypes, countries_plus, emplacement, geosite, languages_plus, location, membershiporganization, membershipperson, organization, person, reversion, sessions, sites, source, violation
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying source.0001_initial... OK
  Applying violation.0001_initial... OK
  Applying violation.0002_auto_20151102_2237... OK
  Applying source.0002_auto_20160513_1741... OK
  Applying source.0003_auto_20160513_1944... OK
  Applying source.0004_auto_20160513_2044... OK
  Applying source.0005_auto_20160531_2028... OK
  Applying source.0006_auto_20160531_2148... OK
  Applying source.0007_auto_20160601_1624... OK
  Applying source.0008_auto_20160601_1714... OK
  Applying source.0009_auto_20160615_1511... OK
  Applying source.0010_auto_20160728_2006... OK
  Applying source.0011_auto_20160729_1819... OK
  Applying source.0012_auto_20160805_1705... OK
  Applying source.0013_auto_20160805_1943... OK
  Applying source.0014_auto_20160805_2031... OK
  Applying person.0001_initial... OK
  Applying person.0002_alias... OK
  Applying person.0003_auto_20160623_2130... OK
  Applying person.0004_auto_20160810_1741... OK
  Applying person.0005_auto_20160810_2017... OK
  Applying person.0006_person_uuid... OK
  Applying organization.0001_initial... OK
  Applying organization.0002_auto_20160617_1413... OK
  Applying organization.0003_auto_20160623_1640... OK
  Applying organization.0004_auto_20160623_1950... OK
  Applying organization.0005_auto_20160810_1741... OK
  Applying organization.0006_auto_20160810_2017... OK
  Applying organization.0007_organization_uuid... OK
  Applying violation.0003_auto_20160628_2156... OK
  Applying violation.0004_auto_20160629_2015... OK
  Applying violation.0005_auto_20160810_1741... OK
  Applying violation.0006_auto_20160810_2017... OK
  Applying source.0015_source_user... OK
  Applying source.0016_auto_20160811_1711... OK
  Applying violation.0007_classification_violationperpetratorclassification... OK
  Applying violation.0008_auto_20160812_1559... OK
  Applying violation.0009_violation_uuid... OK
  Applying source.0017_auto_20160826_2057... OK
  Applying violation.0010_auto_20161107_2231... OK
  Applying violation.0011_violationfirstallegation_violationlastupdate_violationstatus... OK
  Applying geosite.0001_initial... OK
  Applying geosite.0002_auto_20160622_1459... OK
  Applying geosite.0003_auto_20160628_2156... OK
  Applying geosite.0004_auto_20160810_1741... OK
  Applying geosite.0005_auto_20160810_2017... OK
  Applying geosite.0006_geositefirstcited_geositelastcited... OK
  Applying geosite.0007_geositeopenended... OK
  Applying geosite.0006_auto_20161107_1946... OK
  Applying geosite.0008_merge... OK
  Applying geosite.0009_auto_20161108_2229... OK
  Applying geosite.0010_auto_20161230_1629... OK
  Applying geosite.0011_auto_20170907_1558... OK
  Applying geosite.0012_auto_20170907_1627... OK
  Applying violation.0012_violationsite... OK
  Applying violation.0013_auto_20170915_1614... OK
  Applying source.0018_auto_20180530_1537... OK
  Applying source.0020_auto_20180601_1832... OK
  Applying source.0021_auto_20180604_1605... OK
  Applying source.0022_auto_20180604_1610... OK
  Applying source.0023_auto_20180604_1610... OK
  Applying source.0024_auto_20180606_2037... OK
  Applying organization.0008_organizationheadquarters... OK
  Applying organization.0009_auto_20170117_1521... OK
  Applying organization.0010_organizationfirstciteddate_organizationlastciteddate_organizationopenended_organizationrealstart... OK
  Applying organization.0011_organizationheadquarters... OK
  Applying membershipperson.0001_initial... OK
  Applying membershipperson.0002_auto_20160810_1741... OK
  Applying membershipperson.0003_auto_20160810_2017... OK
  Applying membershiporganization.0001_initial... OK
  Applying membershiporganization.0002_auto_20161214_1451... OK
  Applying membershiporganization.0003_auto_20161214_1456... OK
  Applying membershiporganization.0004_auto_20161214_1525... OK
  Applying membershiporganization.0005_membershiporganizationopenended_membershiporganizationrealstart... OK
  Applying membershiporganization.0006_auto_20170907_1853... OK
  Applying emplacement.0001_initial... OK
  Applying emplacement.0002_auto_20160810_1741... OK
  Applying emplacement.0003_auto_20160810_2017... OK
  Applying emplacement.0004_emplacementopenended... OK
  Applying emplacement.0005_auto_20170905_2006... OK
  Applying emplacement.0006_emplacementrealstart... OK
  Applying emplacement.0007_auto_20170908_1835... OK
  Applying composition.0001_initial... OK
  Applying composition.0002_auto_20160714_1621... OK
  Applying composition.0003_auto_20160810_1741... OK
  Applying composition.0004_auto_20160810_2017... OK
  Applying composition.0005_compositionopenended... OK
  Applying composition.0006_auto_20170905_2006... OK
  Applying composition.0007_compositionrealstart... OK
  Applying area.0001_initial... OK
  Applying association.0001_initial... OK
  Applying association.0002_auto_20160810_1741... OK
  Applying association.0003_auto_20160810_2017... OK
  Applying association.0004_associationopenended... OK
  Applying association.0005_auto_20170905_2006... OK
  Applying area.0002_auto_20160622_1459... OK
  Applying area.0003_auto_20160810_1741... OK
  Applying area.0004_auto_20160810_2017... OK
  Applying area.0005_auto_20161107_1946... OK
  Applying area.0005_areafirstcited_arealastcited... OK
  Applying area.0006_merge... OK
  Applying area.0007_auto_20161108_2201... OK
  Applying area.0008_auto_20161108_2229... OK
  Applying area.0009_auto_20161230_1629... OK
  Applying source.0025_auto_20180606_2041... OK
  Applying source.0026_auto_20180606_2042... OK
  Applying source.0027_auto_20180608_1401... OK
  Applying source.0030_auto_20180705_1535... OK
  Applying source.0031_auto_20180705_1536... OK
  Applying area.0010_auto_20180706_1715... OK
  Applying location.0001_initial... OK
  Applying location.0002_location_geometry... OK
  Applying location.0003_auto_20180918_1833... OK
  Applying location.0004_location_admin_level... OK
  Applying location.0005_remove_location_admin_level... OK
  Applying association.0006_auto_20180706_1825... OK
  Applying association.0007_auto_20181018_1551... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying composition.0008_auto_20180706_1825... OK
  Applying composition.0009_auto_20180824_1840... OK
  Applying composition.0010_auto_20180824_1842... OK
  Applying composition.0011_auto_20180824_1843... OK
  Applying composition.0012_auto_20180824_1845... OK
  Applying countries_plus.0001_initial... OK
  Applying countries_plus.0002_auto_20150120_2225... OK
  Applying countries_plus.0003_auto_20150611_1446... OK
  Applying countries_plus.0004_auto_20150616_1242... OK
  Applying countries_plus.0005_auto_20160224_1804... OK
  Applying emplacement.0008_auto_20180706_1825... OK
  Applying emplacement.0009_auto_20180820_1923... OK
  Applying emplacement.0010_auto_20180820_1924... OK
  Applying emplacement.0011_auto_20180820_1925... OK
  Applying emplacement.0012_auto_20180820_1927... OK
  Applying emplacement.0013_auto_20181018_1538... OK
  Applying geosite.0013_auto_20180706_1825... OK
  Applying languages_plus.0001_initial... OK
  Applying languages_plus.0002_auto_20141008_0947... OK
  Applying location.0006_auto_20181113_1627... OK
  Applying location.0007_auto_20181113_1630... OK
  Applying location.0008_location_adminlevel... OK
  Applying membershiporganization.0007_auto_20180706_1825... OK
  Applying membershipperson.0004_auto_20180706_1825... OK
  Applying membershipperson.0005_auto_20180813_2103... OK
  Applying membershipperson.0006_auto_20180813_2105... OK
  Applying membershipperson.0007_auto_20180813_2107... OK
  Applying membershipperson.0008_auto_20180814_1449... OK
  Applying organization.0012_auto_20180706_1721... OK
  Applying organization.0013_auto_20180820_2010... OK
  Applying organization.0014_auto_20180820_2011... OK
  Applying organization.0015_auto_20180820_2013... OK
  Applying organization.0016_auto_20180820_2014... OK
  Applying organization.0017_auto_20181227_1414... OK
  Applying violation.0014_auto_20180706_1825... OK
  Applying person.0007_auto_20180706_1825... OK
  Applying source.0033_auto_20180706_1837... OK
  Applying source.0034_auto_20180711_2034... OK
  Applying person.0008_auto_20180724_1439... OK
  Applying person.0009_auto_20180724_1441... OK
  Applying person.0010_delete_alias... OK
  Applying person.0011_personbiography_persondateofbirth_persondateofdeath_persondeceased_personexternallink_persongender_p... OK
  Applying person.0012_auto_20180727_1335... OK
  Applying person.0013_person_published... OK
  Applying reversion.0001_squashed_0004_auto_20160611_1202... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
  Applying source.0035_auto_20180820_1829... OK
  Applying violation.0015_auto_20180821_1441... OK
  Applying violation.0016_auto_20180821_1443... OK
  Applying violation.0017_auto_20180821_1452... OK
  Applying violation.0018_auto_20180821_1457... OK
  Applying violation.0019_auto_20181018_2151... OK
  Applying violation.0020_auto_20181102_1638... OK
  Applying violation.0021_auto_20181102_1830... OK
  Applying violation.0022_auto_20181227_1415... OK
```

**Comment by tlongers** [comment]
@fgregg can you give a bit more detail about the significance/severity of this?

**Comment by fgregg** [comment]
between @jeancochrane and me, we've resolved this.
