### ISSUE TITLE
update_countries_plus error

### ISSUE THREAD

**Issue by jpmckinney** [security-force-monitor/sfm-cms#98]
Here's the traceback:

```
Traceback (most recent call last):
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/countries_plus/utils.py", line 256, in parse_geonames_data
    country = Country.objects.get(iso=clean_data['iso'])
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
countries_plus.models.DoesNotExist: Country matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/countries_plus/utils.py", line 260, in parse_geonames_data
    country = Country.objects.create(**clean_data)
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/countries_plus/models.py", line 99, in save
    self.full_clean()
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/django/db/models/base.py", line 1144, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'area': ['Ensure that there are no more than 1 decimal place.']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/countries_plus/management/commands/update_countries_plus.py", line 10, in handle
    num_updated, num_created = update_geonames_data()
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/countries_plus/utils.py", line 215, in update_geonames_data
    return parse_geonames_data(r.iter_lines())
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/countries_plus/utils.py", line 262, in parse_geonames_data
    raise GeonamesParseError("Unexpected field length: %s" % e.message_dict)
countries_plus.utils.GeonamesParseError: I couldn't parse the Geonames file (http://download.geonames.org/export/dump/countryInfo.txt).  The format may have changed. An updated version of this software may be required, please check for updates and/or raise an issue on github.  Specific error: Unexpected field length: {'area': ['Ensure that there are no more than 1 decimal place.']}
```

**Comment by evz** [comment]
Woops, requirements updated

**Comment by jpmckinney** [comment]
Thanks!
