### ISSUE TITLE
python manage.py import_google_doc error

### ISSUE THREAD

**Issue by jpmckinney** [security-force-monitor/sfm-cms#99]
`python manage.py import_google_doc --help` produces `ImportError: cannot import name 'util'`.

Traceback:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/django/core/management/__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/james/Sites/code/opennorth/miscellaneous/sfm-cms/sfm_pc/management/commands/import_google_doc.py", line 12, in <module>
    from apiclient.discovery import build
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/apiclient/__init__.py", line 18, in <module>
    from googleapiclient import channel
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/googleapiclient/channel.py", line 63, in <module>
    from googleapiclient import errors
  File "/Users/james/.virtualenvs/sfm-cms/lib/python3.5/site-packages/googleapiclient/errors.py", line 26, in <module>
    from oauth2client import util
ImportError: cannot import name 'util'
```

**Comment by evz** [comment]
D'oh. Just ran into this myself. For some reason I was able to fix it by updating the version of the Google API SDK to the most recent version (1.5.4). Not sure why that worked before.
